### ISSUE TITLE
How to use ExVCR with Finch?

### ISSUE THREAD

**Issue by danicuki** [keathley/finch#108]
My project uses [Finch](https://github.com/keathley/finch) to make parallel HTTP requests.

I tried to add VCR to my tests, but the HTTP requests are still happening.

Here is my test:
```elixir
defmodule MyClientTest do
  use ExUnit.Case, async: true
  use ExVCR.Mock #, adapter: ExVCR.Adapter.Httpc

  setup do
    ExVCR.Config.cassette_library_dir("fixture/vcr_cassettes")
    :ok
  end

  test "list_apps" do
    use_cassette "list_apps" do
      list_apps = MyClient.list_apps
      assert MyClient.list_apps == ["app1", "app2"]
    end
  end

end
```

I see a `list_apps.json` file in the `fixture/vcr_cassettes`, but its content is only `[]`

Here is my MyClient module:

```elixir
defmodule MyClient do
  alias Finch.Response

  def child_spec do
    {Finch,
     name: __MODULE__,
     pools: %{
       "https://myapp.com" => [size: 100]
     }}
  end

  def applications_response do
    :get
    |> Finch.build("https://myapp.com/v2/apps.json")
    |> Finch.request(__MODULE__)
  end

  def handle_applications_response({:ok, %Response{body: body}}) do
    body
    |> Jason.decode!()
    end
  end

  def list_apps do
    handle_applications_response(applications_response())
  end

end

```

How to apply VCR to this example?

**Comment by sneako** [comment]
I have never used this library but it's readme lists the http clients that it currently supports and Finch is not included.

Taking a quick look at the code, each supported client has its own implementation within the ExVCR library, so you would have to add a Finch implementation to the library of you wanted to use them together.

https://www.github.com/parroty/exvcr/tree/master/lib%2Fexvcr%2Fadapter

**Comment by wojtekmach** [comment]
ExVCR works by intercepting requests from a given HTTP client but you need to tell it which one, that's the `:adapter` option to `use ExVCR.Mock`. So in order to use it with Finch, someone would need to write such adapter.

You've already created https://github.com/parroty/exvcr/issues/166 which I think is the right place to ask that question, I'd close this issue then.

I'd just add that in the absence of finch adapter exvcr, I would consider other options. Personally I really like https://hex.pm/packages/bypass because it's http client agnostic, and it shouldn't be too hard to build an exvcr-like recording capabilities on top.
