### ISSUE TITLE
Finch defaults to :http1 for dynamic requests

### ISSUE THREAD

**Issue by minhajuddin** [keathley/finch#117]
The following code uses `http1` to make a request even though the hex.pm server supports `http2`.

```elixir
Finch.start_link(name: MyFinch)
Finch.build(:get, "https://hex.pm") |> Finch.request(MyFinch)
```
This happens because the default type here evaluates to `:http1` https://github.com/keathley/finch/blob/main/lib/finch/pool_manager.ex#L61 Ideally, the type of pool should be decided by whether the server supports http2.

![image](https://user-images.githubusercontent.com/43916/107838257-06f02480-6d73-11eb-934f-497423137956.png)

**Comment by keathley** [comment]
The pool choice here matters quite a bit since http/1.1 and http/2 pool solutions aren't compatible with each other. Which pool you want to use should be a conscious choice since you'll need to adjust your pool requirements based on the version. There's not a clean way to determine what pool to use after we've already made the initial request because you need to start a pool before you can make the request in the first place.

What makes an http client efficient is how it reuses connections which is really what Finch is doing for you. If you only need to make a single request, Finch is going to provide little to no value to you.

**Comment by minhajuddin** [comment]
I am planning to build an agent for our services that does the job of sending HTTP requests to all external APIs and it probably won't know beforehand all the endpoints it will be talking to. Is there a way to update the configuration on the fly? I could probably do it whenever I see a new endpoint by probing the endpoint.
