### ISSUE TITLE
Pool Size default (for HTTP/1.1)  is too low

### ISSUE THREAD

**Issue by SophisticaSean** [keathley/finch#124]
I've been comparing different adapters for use in Tesla and I believe the default pool size setting for Finch is too low to be comparable to other adapter defaults.

Request per second:
- Finch default pool size of 10: `RPS: 198.13284094832753`
- Hackney default: `RPS: 932.1966376616629`
- HTTPC default: `RPS: 3225.471319940388`
- Finch pool size of 50: `RPS: 956.4245735627867`

These were all tested the exact same way, the only difference is the Tesla adapter used for the requests.

I'm happy to make an PR to adjust the default pool size to be more in line with other libraries.

**Comment by keathley** [comment]
Hey @SophisticaSean. Did you get these values with http/1.1 or http/2 pools? My assumption is that its http/1.1 but I wanted to make sure. I could see us increasing the size of the http/1.1 pool defaults since the connections are opened lazily and can only be used by a single connection at a time. I would be really surprised if we needed to open 50 http/2 connections to achieve similar results. My intuition is that in real-world scenarios that would actually result in a net decrease in performance due to the additional resource utilization. But I could be wrong about that.

**Comment by SophisticaSean** [comment]
My apologies, these were all done on http/1.1 pools vs an http 1.1 server written in Go. I have not experimented with RPS on http/2 pools yet and my current primary use case of Finch is for http 1.1 communication.

**Comment by SophisticaSean** [comment]
bump
