### ISSUE TITLE
HTTP/2

### ISSUE THREAD

**Issue by sneako** [keathley/finch#25]
So far, we have focused on HTTP/1, but since HTTP/2 allows multiplexing, a different pooling strategy should perform even better. We probably want to just start a group of connections, register them in the Registry, and round-robin, LRU, or randomly choose one instead.

We need to allow users to explicitly choose which protocol (and therefore pooling strategy) to use, unless we can efficiently determine if the server supports H2 and then automatically choose the correct pooling strategy.

**Comment by whatyouhide** [comment]
@sneako IIRC there are ways to determine if the server supports HTTP/2. One would be to open a connection and negotiate the protocol, and then close the connection right away once we know that HTTP/2 is supported. Then we can open the right pool.

I would suggest to start with explicit protocol from the user though. I have an HTTP/2 pool built out already https://github.com/elixir-mint/mint_pool/blob/master/lib/mint_pool/single_host/http2.ex. Thoughts on this? I would love to contribute this feature btw, since I have experience with HTTP/2 and also obvious Mint experience 😄

**Comment by keathley** [comment]
I have a branch started for this. Unfortunately I've been slightly...distracted XD. So in the meantime I'm happy to move forward whatever way is most efficient. Happy to have help @whatyouhide :). 

I definitely think we should make the choice of the pool type explicit for now. Its probably even worth raising an error if the user wants an http2 pool and mint can't negotiate the http2 connection. Otherwise the user may not understand which pool is being used which would make it harder to diagnose performance problems.

**Comment by sneako** [comment]
Thanks for chiming in @keathley! I knew you had started working on this, so I didn't want to give the green light without talking to you first. 

I agree we should start with allowing the user to be explicit about the protocol they intend to use.

I really like the :gen.statem approach @whatyouhide has started with and [described here](https://andrealeopardi.com/posts/connection-managers-with-gen_statem/)!

**Comment by keathley** [comment]
Yup that seems good to me.

**Comment by whatyouhide** [comment]
I finally had some time to start working on this. I have a few questions on the direction I should take:

1. HTTP/2 connections are meant to be open for as long as needed. Should we close them after a timeout of inactivity? It's very easy to do with `:gen_statem` timeouts.

1. Should we reconnect a connection if it goes down? This is a larger question: should we open connections on demand when they're needed up to the `:size` maximum, or should we open `:size` connections when starting the pool and?

I guess all the questions conflate in the second part of 2. 😄

**Comment by sneako** [comment]
For HTTP/1, the first implementation eagerly opened connections as soon as each pool worker was started, and would reconnect connections as they were closed. This worked quite well when the server supported keepalive, but in cases where the server did not, we would see connections constantly being opened and closed before we could even use them, and sometimes we wouldn't even be able to finish starting up the pool.

I switched to opening the connections in the caller, if the caller receives a closed connection. This works well in both situations. When the server supports keepalive, then the caller will almost always receive an open connection, so I did not notice any significant performance degradation.

With HTTP/2 however, I don't think we need to worry about that, so maybe we can get away with eagerly opening the connections, and reconnecting them when they get closed, since the protocol was designed for long lived connections from the beginning.

Curious to hear what others think as well, but I think we can start with eagerly opening connections. 

I think we should also allow the user to configure an idle timeout as proposed in your first point.

**Comment by whatyouhide** [comment]
@sneako idle timeout and reconnections are a bit against each other. If we implement an idle timeout, it means that we'll have to open the connection as soon as the next request hits it (on demand). This design works better with a lazy pool where we connect on demand for all cases and keep the connection alive for a while. Otherwise, we go all the way on always-on connections, that connect eagerly when the pool is started and reconnect on failures. Thoughts?

**Comment by sneako** [comment]
Ah yeah good point, I guess we don't need idle timeouts if we have the always-on connections. I wanted to use always-on connections for everything, but only backed out on HTTP/1 after hitting the failure mode I described, so as long as we don't anticipate something similar happening in HTTP/2, I vote for always-on

**Comment by keathley** [comment]
@whatyouhide Thanks for working on this. I had started an http2 branch to make it easier to support both http1 and http2 pools. But I hadn't finished porting over the logic from mint_pool to finch. If you want I can submit a PR for the work to decouple the http1 pool. Which should make it easier to add an http2 pool in. Lemme know if that's helpful.

As far as your actual questions, I think we should go with eager connections and maintain a persistent set of connections, as opposed to growing and shrinking the pool as required. It makes it a lot easier to reason about concurrency limits and tuning throughput that way. Because the http2 connections will be inside a dedicated process it's a little easier to manage than http1 connections.

**Comment by keathley** [comment]
#49 is open now. Lemme know what y'all think.
