### ISSUE TITLE
HTTP method api?

### ISSUE THREAD

**Issue by keathley** [keathley/finch#6]
I was wondering if we should support the standard "HTTP method" API in Finch. I'm content to use the single `request` function and specify the method as an atom. But I figured I would see what others thought.

**Comment by sneako** [comment]
I'm not sure if we need to add these methods, but I am not strictly opposed to the idea. I imagine many users will wrap their Finch usage in another function, to avoid passing in the :name argument all the time, so if they really want this api they could easily add functions for the methods they need.

**Comment by wojtekmach** [comment]
With this, we'd be able to:

1. `Finch.request(:get, ...)`
2. `Finch.request("GET", ...)`
3. `Finch.get(...)`

all of them have their place but altogether seems perhaps a bit much? Not sure which I'd personally keep but thought I'd bring this up anyway.

An advantage of having a `get` in particular is it would not have request body so one argument less. ([technically it should support request body but not really](https://stackoverflow.com/questions/978061/http-get-with-request-body))

**Comment by QuinnWilton** [comment]
> An advantage of having a get in particular is it would not have request body so one argument less. (technically it should support request body but not really so maybe it is not an advantage after all)

My use case requires sending bodies with `get` requests, so that flexibility would be helpful for me at least. Servers should ignore the body for a `get` request, but in my experience, many applications require data to be passed in it.

Supporting `Finch.request(method, ...)` with arbitrary methods also allows Finch to be used with protocols that define their own HTTP methods, like the `NOTIFY` and `POLL` methods from [GENA](https://tools.ietf.org/html/draft-cohen-gena-p-base-01)

**Comment by whatyouhide** [comment]
In my experience, I never ever use the HTTP method functions and always go for `request(method, ...)`. In general, I tend to pretty often build mocks for my HTTP client in order to have a defined interface and in order to test different scenarios, and it's much nicer to build a mock for a smaller API surface that is generic enough to cover all usages. Keeping the API surface small means less code to maintain, less documentation to show, less overhead for users. In this case, I am for keeping only `request`. My 2 cents!

**Comment by sneako** [comment]
Thanks for all of the great input everyone! I think we are going to stick with just the request function for now.
